### ISSUE TITLE
Simulate signal events with LYSO in MadGraph

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#17]
## Issue description

The collab is heavily considering an active target (LYSO). We should simulate events with interacting with LYSO

## Tasks

- [ ] Reproduce dark photon production as is
- [ ] Change target to Y
- [ ] Change target to the full composite (?)

## Existing material to start off

 * LYSO composite https://github.com/LDMX-Software/ldmx-sw/blob/trunk/Detectors/data/ldmx-lyso-v12/target.gdml#L36-L40
 * Dark bremsstrahlung repo: https://github.com/LDMX-Software/dark-brem-lib-gen/tree/main
