### ISSUE TITLE
Photophobic ALPs

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#19]
## Issue description

Can we produce Photophobic ALPs at SLAC?

## Tasks

- [ ] Reproduce LHC running
- [ ] Port to SLAC conditions
- [ ] If it works, plug it into LDMX

## Existing material to start off

 * Theory paper: https://arxiv.org/abs/1805.06538
 * UFO: https://cms-project-generators.web.cern.ch/cms-project-generators/ALP_Photophobic_UFO.tar.gz

**Comment by tvami** [comment]
The outcome of this is merged in https://github.com/IncandelaLab/LDMX-scripts/pull/101
