### ISSUE TITLE
Getting started with standalone MadGraph + Pythia

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#20]
## Issue description

General exploration of MadGraph + Pythia in standalone mode

## Tasks

- [x] Produce gluino events out of the box with CMS cards
- [x] Create LHE events with 0,1,2 jets and compare them (pT, E, phi, eta)
- [x] Create the HEPMC files with Pythia and compare them to the LHE content

## Existing material to start off

 * CMS gluino SMS card example: https://cms-pdmv-prod.web.cern.ch/mcm/public/restapi/requests/get_setup/SUS-RunIISpring21UL18FSGSPremixLLPBugFix-00025
 * Pythia Manual https://arxiv.org/pdf/2203.11601.pdf

**Comment by tvami** [comment]
Done and presented at 
https://indico.cern.ch/event/1377622/contributions/5789689/attachments/2790793/4868156/Mad%20Graph%20Asahi%20(1_31_24)%20.pdf
