### ISSUE TITLE
dEdx in Tracker

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#21]
## Tasks

- [x] Produce kaon gun, pion, e gun
- [x] #25
- [x] Get the rechit energy
- [ ] Figure out the angle of the tracks
- [x] Calculate dEdx and plot against the momentum
- [x] Transform to Ih to see if that's any better
- [x] Include hits from the tracker
- [x] Repeat everything with a eN sample

## Existing material to start off

 * dEdx in CMS HSCP https://cms.cern.ch/iCMS/user/noteinfo?cmsnoteid=CMS%20AN-2022/129

**Comment by tvami** [comment]
The samples for eN are here
https://cernbox.cern.ch/files/link/public/lygH4vZkyInVlOj?tiles-size=1&items-per-page=100&view-mode=resource-table

The tune `G18_02a_02_11b` is better to start with

**Comment by tvami** [comment]
PR to implement the first pass in https://github.com/LDMX-Software/ldmx-sw/pull/1510
