### ISSUE TITLE
Simulate events with LYSO in LDMX

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#23]
## Issue description

Continuation of https://github.com/IncandelaLab/LDMX-scripts/issues/17 

## Tasks

- [x] Compare `ldmx-lyso-v12` to `ldmx-v12`
- [x] Make  `ldmx-lyso-v14`
- [ ] Run ldmx with all three DM masses and compare to official samples

## Existing material to start off

 * https://github.com/LDMX-Software/ldmx-sw/blob/trunk/Detectors/data/ldmx-lyso-v12/constants.gdml
 * https://github.com/LDMX-Software/ldmx-sw/blob/trunk/Detectors/data/ldmx-v12/constants.gdml
 * for running on the new library https://github.com/LDMX-Software/ldmx-sw/blob/trunk/.github/validation_samples/signal/config.py

**Comment by tvami** [comment]
Talk from the LDMX week
https://indico.fnal.gov/event/62016/contributions/278827/subcontributions/9307/attachments/174111/236033/LYSO4LDMX202401.pdf
