### ISSUE TITLE
ParticleNet with 2e

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#31]
## Tasks

- [ ] Make samples with a gun with 2 electrons, with different angular separation between the two
- [ ] Plot out observables that show how the showers differ from the 1e case
- [ ] Run ParticleNet and see what it can do to resolve the two showers

## Existing material to start off

 * ParticleNet https://github.com/IncandelaLab/LDMX-scripts/issues/26
 * MultiParton config file (but set to 1e for now): https://gist.github.com/tvami/c7afa653e4cadb7b0eb5021293a9500e

**Comment by DuncanWilmot** [comment]
@tvami Is this config file ready to run, with just adjustment to ```nElectrons``` variable?

**Comment by tvami** [comment]
Yes, but that's for the 2e sample so that's a bit of a simplification. For the real pile-up electron you need to have some input, the pileup.root file and then can use
https://github.com/LDMX-Software/ldmx-sw/blob/trunk/.github/validation_samples/it_pileup/config.py to create the final sample
