### ISSUE TITLE
WAB studies with reduced ECAL

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#32]
## Tasks

- [x] Take the geometry produced in https://github.com/IncandelaLab/LDMX-scripts/issues/16
- [x] Run on the WAB samples from Billy
- [x] Measure the angles

**Comment by tvami** [comment]
Done and presented at https://indico.cern.ch/event/1389997/contributions/5844011/attachments/2814615/4913246/Sanjit%2003.06%20Update.pdf
