### ISSUE TITLE
eN measurement on 8 GeV data

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#33]
## Tasks

- [x] Look at the samples located in POD under
```
/home/vamitamas/Samples8GeV/eN-genie
```

- [x] Make sure we can reconstruct the electron
- [x] Measure the angles and energy transfer

## Existing material to start off

 * https://github.com/IncandelaLab/LDMX-scripts/issues/25

**Comment by fdelzanno** [comment]
The sample has no reconstructed Tagger tracks, so we can only reconstruct the electron from the Recoil Tracks. There are 24420 particles in the sample, distributed as:
- 19041 Electrons (PDGID 11)
- 208 Positrons (PDGID -11)
- 2384 Protons (PDGID 2212 or -2212)
- 2587 Pions (PDGID 211 or -211)
- 181 Kaons (PDGID 321 or -321)
- 19 Sigma Baryons (PDGID 3112 or 3222)

![Histogram of Recoil Tracks pdgID_genie](https://github.com/IncandelaLab/LDMX-scripts/assets/98343919/78cb26c0-86ee-49fb-84fb-0add04389ca4)

**Comment by fdelzanno** [comment]
Angle of electron momentum off the beam axis (z) reconstructed from global perigee information (in radians and degrees):

![Histogram of Recoil Tracks beamAngle_genie](https://github.com/IncandelaLab/LDMX-scripts/assets/98343919/ff1e7e67-3c92-4929-a058-6dd45c0dbcaa)
![Histogram of Recoil Tracks beamAngle_genie (degree)](https://github.com/IncandelaLab/LDMX-scripts/assets/98343919/de7f46cd-e65f-4d8f-ac05-5c0d7d235900)
