### ISSUE TITLE
eN measurement on 4 GeV with reduced-LDMX

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#34]
## Tasks

- [x] Need to figure out how to do tracking with 2 (double)layers
- [x] Take reduced geometry introduced in https://github.com/LDMX-Software/ldmx-sw/pull/1268
- [x] Tweak the parameters or redo tracking for this situation
- [x] Do the same as in https://github.com/IncandelaLab/LDMX-scripts/issues/33

## Existing material to start off

 * Source 1
 * Source 1
