### ISSUE TITLE
Non-fiducial ECal ParticleNet Study

### ISSUE THREAD

**Issue by DuncanWilmot** [IncandelaLab/LDMX-scripts#35]
## Issue description
Train ECal ParticleNet on non-fiducial events to determine whether this subset is problematic for an ECal-only ParticleNet model. We are planning to have two people work on this project and compare results to cross-validate 

## Tasks

- [ ] Skim events with a cut that removes all fiducial events (my current thinking is to use a shared directory of processed files and make the additional fiducial cut in dataset.py instead of file_processor.py) 
- [ ] Train and Evaluate ParticleNet on these events
- [ ] Plot results (ROC curves and pT bias)

## Existing material to start off

 * A description of fiducial events and some example code can be found at [Issue#27](https://github.com/IncandelaLab/LDMX-scripts/issues/27)
 * You can take a look at some [v14 ParticleNet code](https://github.com/DuncanWilmot/LDMX-scripts/tree/lazy-loading/GraphNet) but keep in mind this is in development and some of it includes HCal information
 * I will organize a more succinct directory with stable v14 ECal ParticleNet code. Once that is done I will merge it with IncandelaLab LDMX-scripts and update this issue with a link to the new directory

**Comment by aether-2023** [comment]
Missing cellmodule.txt for v14 (LDMX-scripts/GraphNet/data/v14), which is needed when comparing ECal face projection of incoming particle and the ECal cells position. Did cellmodule.txt changed for v13 and v14? May I use the v12 cell geometry for non-fiducial study?

**Comment by DuncanWilmot** [comment]
@aether-2023 Answered on Mattermost but the file is at ```/home/duncansw/LDMX-scripts/GraphNet/data/v13/cellmodule.txt```. Same for v14 as for v13

**Comment by tvami** [comment]
@DuncanWilmot I found this branch in ldmx-sw, it seems David tried to have it all in ldmx-sw, but maybe it's all outdated at this point:
https://github.com/LDMX-Software/ldmx-sw/compare/nonfiducial-filter?expand=1
We should think about what to do with this branch
