### ISSUE TITLE
Reduced-ECAL: Add extra absorber as a preshower

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#38]
## Tasks

- [x] Modify the GDML so it includes more W in front of the ECAL
- [x] Study how much of the shower we can contain like that
- [x] Make a new `v2` geometry if it works better

## Existing material to start off

 * This is a continuation of https://github.com/IncandelaLab/LDMX-scripts/issues/16

**Comment by tvami** [comment]
Done in https://github.com/LDMX-Software/ldmx-sw/pull/1489
