### ISSUE TITLE
Compare different DM models in MadGraph

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#40]
## Issue description

LDMX currently uses MadGraph4 which didnt actually use UFOs, we need to develop one. 

## Tasks

- [x] Reproduce current production
- [x] Understand the differences between the UFOs below
- [x] Add the nucleus addition
- [x] Compare the kinematics + cross sections

## Existing material to start off

 * https://cms-project-generators.web.cern.ch/cms-project-generators/pscalar_darkphoton_UFO.zip
 * https://github.com/ymzhong/mg5_aMC_tutorial/tree/main/DarkPhoton_UFO
 * iDM model: https://github.com/tomeichlersmith/hps/tree/main/idm/mg-model
 * Current production: https://github.com/LDMX-Software/dark-brem-lib-gen/tree/main
 * To read the produced LHE files, here is an example snippet
https://gist.github.com/tvami/a69d4f9b16e809e546bba84a371df499

**Comment by tvami** [comment]
We concluded that the iDM model is a good proxy for whatever we have used in the past. PR in https://github.com/LDMX-Software/dark-brem-lib-gen/pull/19
