### ISSUE TITLE
Follow the electron and see if it ends up in side HCAL

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#47]
## Tasks

- [ ] Project the electron path from the target SP 
- [ ] Check how often we end up in side-HCAL for different masses of signals
- [ ] Change HCAL veto to gain back more signal

## Existing material to start off

 * Non-fid signal in HCAL part: https://tvami.web.cern.ch/tvami/projects/LDMX/v4_nonfid/CompareSamples_v4_nonfid/CutBasedDM_Hcal_MaxSector.png
