### ISSUE TITLE
Change digitizer sensor thickness to 400um

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#48]
## Issue description

Currently the digitizer assumes 300um sensor thickness
https://github.com/LDMX-Software/ldmx-sw/blob/trunk/Ecal/python/digi.py#L74

while in reality this will 400um.  

## Tasks

- [ ] Follow the steps https://github.com/IncandelaLab/LDMX-scripts/blob/master/EnergyResStudies/README.md
- [x] Run the electron gun but have the thickness at 0.4 see, the resources below 
- [ ] Show the energy resolution plots

Later on
 - [ ] Produce DQM histograms for default
 - [ ] Produce DQM histograms for the changed sensor size
 - [ ] Compare the two

## Existing material to start off

 * Electron gun with 400 um Si: https://github.com/IncandelaLab/LDMX-scripts/blob/master/EnergyResStudies/electron_gun_config.py
 *  Use the config files from the validation module with the branch that has the changes
 * https://github.com/IncandelaLab/LDMX-scripts/tree/master/EnergyResStudies
