### ISSUE TITLE
Charged-lepton flavor-violating processes in LDMX

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#49]
## Issue description

Are we sensitive to mu --> eee ? or mu --> e gamma ?

## Tasks

- [ ] Use the UFO in https://feynrules.irmp.ucl.ac.be/wiki/RPVMSSM 
- [ ] Generate LHE events like mu --> eee and mu --> e gamma 
- [ ] Plug it into LDMX-sw and look at the distributions

## Existing material to start off

 * https://arxiv.org/pdf/2209.00142
 * https://feynrules.irmp.ucl.ac.be/wiki/RPVMSSM
