### ISSUE TITLE
WABs with 2e samples

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#51]
## Tasks

- [x] Let's get started with a 2e gun
- [x] Then we need to project to ECAL
- [x] Then move to make a 1e WAB sample and overlay with a 1e inclusive sample
- [x] Carry out the measurement for WABs

## Existing material to start off

 * Source 1
 * Source 1

**Comment by oscarplewis** [comment]
Samples on the order of 1M 2e WAB events were created and a BDT was trained using these events, but there was no significant improvement compared to the Segmip BDT trained from 1e pN events. My summary slides on this topic are located on Indico [here](https://indico.cern.ch/event/1535617/).

In order to veto 2e WAB events, a different approach will need to be taken, probably based more on tracking than the BDT approach.

**Comment by tvami** [comment]
Can you please also share the location of the samples in POD?
