### ISSUE TITLE
Extrapolate recoil tracks to the ECAL and study the EcalVeto / redo the BDT

### ISSUE THREAD

**Issue by tvami** [IncandelaLab/LDMX-scripts#56]
## Tasks

- [ ] Check how the TrackExtrapolation performed
- [ ] Check how that changes the EcalVeto
- [ ] Retrain the BDT with this

## Existing material to start off

 * Source 1
 * Source 1
